### ISSUE TITLE
Add metas column to Message

### ISSUE THREAD

**Issue by myckhel** [myckhel/laravel-chat-system#19]
Replace `Metas` by adding `metas` column to `Message` model.

metas column schema: `json`

CheckList:
- [x] add `metas` column to message
- [x] delete `Metas` model, migration, trait and relationship
- [x] remove `metas` config refs from chatsystem's `config`
- [x] update `MessageController@store` token creation by using `message.metas` column to store token
- [x] remove metas refs from  `MessageController@index`

**Comment by hmreumann** [comment]
Hallo @myckhel i think i can do with this. I just need to research a little bit about steps 4 and 5. But would be good to understand your project.

**Comment by myckhel** [comment]
Oh nice!

Some times when you have already created database tables like.
**Example** 
| table name | columns | columns |
| --- | --- | --- |
| `my_table` | `my_table_column1` | `my_table_column2` |

and you are likely to add columns to the table like `my_table_column3` which can be sometimes very worrying to add new columns to the tables you have already created.

tables having too much columns can make your db structure looks complicated.

But having a table that serves as an extensions to other tables can make it easier to add rows just as if you are adding columns.

In that case it could be a metas table which has columns: 
|`name` | `value`| `model_id` |
| ----- | --- | ----- |
| my_table_column3 | "column value" | 2 |
| my_table2_column2 | "column value 2" | 3 |

when you query `my_table`: 
you get
| table name | columns | columns |
| --- | --- | --- |
| `my_table` | `my_table_column1` | `my_table_column2` |

you could join the `metas` table to make it look as if they are `my_table` columns

| table name | columns | columns | columns |
| --- | --- | --- | --- |
| `my_table` | `my_table_column1` | `my_table_column2` | `my_table_column3` |

Or you could join the `metas` table to make it a relationship of `my_table`

```json
{
  "id": 1,
  "my_table_column1": "value",
  "my_table_column2": "value",
  "metas": [
    {
      "name": "my_table_column3",
      "value": "value",
    },
  ]
}
```

So that was the purpose of creating the [Meta model](https://github.com/myckhel/laravel-chat-system/blob/master/src/Models/Meta.php).

But now i figured out that it is not necessary to create a separate table to extend other tables columns.
One could also create a metas column which will be a `json` type.
Then your query could give you: 
```json
{
  "id": 1,
  "my_table_column1": "value",
  "my_table_column2": "value",
  "metas": {
      "my_table_column3": "value",
      "my_table_column4": "value",
    },
}
```

So in the context of the project.
after creating the Message model db schema (id, created_at, ...), later on I needed to add `token` column which is likely to be useless for some users.
so i decided to use `Meta` model to manage `token` column.

So now we can migrate from using `Meta` model to json column.

I just hope you understands why using `Meta` model and why need to migrate to json column to achieve same thing `Meta` does.

**Comment by myckhel** [comment]
> Hallo @myckhel i think i can do with this. I just need to research a little bit about steps 4 and 5. But would be good to understand your project.

4. means instead of using `Meta` to create token, use Message.metas column to store the token
example snippet using Meta model to create token
```php
if ($token) {
  $meta = ['name' => 'token', 'value' => $token];
  $message->addMeta($meta, $meta);
}
```

5. means `MessageController@index` doesn't need to query for metas relationship again since metas has been added to the Message as a column

**Comment by hmreumann** [comment]
Hi,
Working on the MessageController@store
At the end i have a line that i guess should be removed `$token && $message->metas->keyValue();` doesn't it?

And in MessageController@index i have the same issue `$messages->map(fn ($msg) => $msg->metas->keyValue());`, should this be removed too?

Thanks, Hernán.

**Comment by myckhel** [comment]
Oh. Nice .
Weldone 

Yes they should be removed

**Comment by hmreumann** [comment]
Ok I will make the pull request for you to see the changes.
I was a little bit confused with the when function after looking for the `$conversation->messages()` but I hope it works. How should I test this kind of changes?
Thank you for your patiens.

**Comment by myckhel** [comment]
Nice!
it could be tested with postman.
collection link https://www.getpostman.com/collections/ce1f970755183b8eb0dd
