### ISSUE TITLE
Class App\Models\User contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (Myckhel\ChatSystem\Contracts\ChatEventMaker::chatEventMakers)

### ISSUE THREAD

**Issue by soumsena** [myckhel/laravel-chat-system#34]
Hello how are you???
 I tried to   implement the
    * `Myckhel\ChatSystem\Contracts\ChatEventMaker` contract, in User Model, but I got an error
    * Class App\Models\User contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (Myckhel\ChatSystem\Contracts\ChatEventMaker::chatEventMakers);  How can i fix that???
    * I noticed in the API that we need 3 variables (name, email and password) to connect, but I only use 2 variables (username and password).
    *  how i want to handle this too???
    * I also tried ChatSystem Broadcast Events;
    
 var current_username = "{{ Auth::user()->username }}";
var current_user = "{{ Auth::user()}}";
var userid = "{{ Auth::id() }}";
            
Echo.private(`message-event.user`+userid)
  .listen('message', (event) => {
    console.log(event)
  })
I got Error 
[01:12:34] - 9BEdhJIOfQvhZG32AAAE could not be authenticated to private-message-event.user.9
{
    "message": "Myckhel\\ChatSystem\\Broadcasting\\Chat\\UserMessageChannel::join(): Argument #2 ($messagesUser) must be of type Myckhel\\ChatSystem\\Broadcasting\\Chat\\User, string given, called in /var/www/eglise.local/vendor/laravel/framework/src/Illuminate/Broadcasting/Broadcasters/Broadcaster.php on line 279",
    "exception": "TypeError",
    "file": "/var/www/eglise.local/vendor/myckhel/laravel-chat-system/src/Broadcasting/Chat/UserMessageChannel.php",
can you help me solve his errors please? Thank you!!!!!!!

**Comment by myckhel** [comment]
- Does your user model looks like this
 ```php
use Myckhel\ChatSystem\Traits\Message\HasMessage;
use Myckhel\ChatSystem\Traits\ChatEvent\CanMakeChatEvent;
use Myckhel\ChatSystem\Contracts\ChatEventMaker

class User extends Authenticatable implements ChatEventMaker
{
    use HasMessage, CanMakeChatEvent;
...
```
Checkout https://github.com/myckhel/chat-system-example/blob/53753dfdb6b8cce95b5cc27937a8fe57dabba2b5/app/Models/User.php#L15

- Does using 2 variables gives you errors?
- I think your broadcast routes must use authentication middleware
E.g
```php

 Broadcast::routes(['middleware' => ['auth:sanctum'], 'prefix' => 'api']);
```
See https://github.com/myckhel/chat-system-example/blob/53753dfdb6b8cce95b5cc27937a8fe57dabba2b5/app/Providers/BroadcastServiceProvider.php#L18

**Comment by soumsena** [comment]
Hi Thx for your help, i did implement the Myckhel\ChatSystem\Contracts\ChatEventMaker contract, in User Model; but the ChatSystem Broadcast Events does not work, when i modified both files, it show other error :
[19:17:05] - Preparing authentication request to: http://localhost:80
[19:17:05] - Sending auth request to: http://localhost:80/broadcasting/auth

⚠ [19:17:12] - -OwJ5yJ7_LU-TOUDAAAC could not be authenticated to private-message-event.user.9
{
    "message": "Undefined variable $messageUser",
    "exception": "ErrorException",
    "file": "/var/www/eglise.local/vendor/myckhel/laravel-chat-system/src/Broadcasting/Chat/UserMessageChannel.php",
, Any idea???

I looked in your file chat-system-example, is very detailed, but it's in React or I'm null in React. 
I can have an example in VUEJS please ???  
thank you very much for your help

**Comment by myckhel** [comment]
I cannot provide example in Vue for now but feel free to ask for assistance on an challenges you might be facing

**Comment by soumsena** [comment]
Hi, how are you doing??? I tried. Thanks a lot for your help; I still have an error
"Undefined variable $messageUser" when i use that

 Echo.private(`message-event.user.{{Auth::id()}}`)
  .listen('message', (event) => {
    console.log(event)
  })

⚠ [19:16:41] - 2t5Qjv6H0aEAdFr8AAAM could not be authenticated to private-message-event.user.9
{
    "message": "Undefined variable $messageUser",

I haven't had a solution yet,

**Comment by soumsena** [comment]
I am using the [vue-advanced-chat ](https://github.com/antoine92190/vue-advanced-chat)package  like the Frontend.
here is an example of my component.
<template>
  <div class="window-container" :class="{ 'window-mobile': isDevice }">
    <form v-if="addNewRoom" @submit.prevent="createRoom">
      <input v-model="addRoomUsername" type="text" placeholder="Add username" />
      <button type="submit" class="button"  :disabled="disableForm || !addRoomUsername">
        Create Room
      </button>
      <button class="button button-cancel" @click="addNewRoom = false">
        Cancel
      </button>
    </form>

    <form v-if="inviteRoomId" @submit.prevent="addRoomUser">
      <input v-model="invitedUsername" type="text" placeholder="Add username" />
      <button type="submit" class="button" :disabled="disableForm || !invitedUsername">
        Add User
      </button>
      <button class="button button-cancel" @click="inviteRoomId = null">
        Cancel
      </button>
    </form>

    <form v-if="removeRoomId" @submit.prevent="deleteRoomUser">
      <select v-model="removeUserId">
        <option default value="">
          Select User
        </option>
        <option v-for="user in removeUsers" :key="user._id" :value="user._id">
          {{ user.username }}
        </option>
      </select>
      <button type="submit" :disabled="disableForm || !removeUserId">
        Remove User
      </button>
      <button class="button-cancel" @click="removeRoomId = null">
        Cancel
      </button>
    </form>

    <chat-window
      :current-user-id="currentUserId"
      :room-id="roomId"
      :rooms="loadedRooms"
      :loading-rooms="loadingRooms"
      :messages="messages"
      :messages-loaded="messagesLoaded"
      :rooms-loaded="roomsLoaded"
      :room-actions="roomActions"
      :menu-actions="menuActions"
      :room-message="roomMessage"
      @fetch-more-rooms="fetchMoreRooms"
      @fetch-messages="fetchMessages"
      @send-message="sendMessage"
      @edit-message="editMessage"
      @delete-message="deleteMessage"
      @open-file="openFile"
      @open-user-tag="openUserTag"
      @add-room="addRoom"
      @room-action-handler="menuActionHandler"
      @menu-action-handler="menuActionHandler"
      @send-message-reaction="sendMessageReaction"
      @typing-message="typingMessage"
    >
    </chat-window>
  </div>
</template>

<script>
// import 'emoji-picker-element';
import date from 'date-and-time';
import ChatWindow from 'vue-advanced-chat'
import 'vue-advanced-chat/dist/vue-advanced-chat.css'
export default {
  components: {
    ChatWindow
  },
  data() {
    return {
      isDevice:false,
      currentUserId: 1234,
      roomsPerPage: 15,
      rooms: [],
      roomId: '',
      startRooms: null,
      endRooms: null,
      roomsLoaded: false,
      loadingRooms: true,
      allUsers: [],
      loadingLastMessageByRoom: 0,
      roomsLoadedCount: false,
      selectedRoom: null,
      messagesPerPage: 20,
      messages: [],
      messagesLoaded: false,
      roomMessage: '',
      startMessages: null,
      endMessages: null,
      roomsListeners: [],
      listeners: [],
      typingMessageCache: '',
      disableForm: false,
      addNewRoom: null,
      addRoomUsername: '',
      inviteRoomId: null,
      invitedUsername: '',
      removeRoomId: null,
      removeUserId: '',
      removeUsers: [],
      roomActions: [
        { name: 'inviteUser', title: 'Invite User' },
        { name: 'removeUser', title: 'Remove User' },
        { name: 'deleteRoom', title: 'Delete Room' }
      ],
      menuActions: [
        { name: 'inviteUser', title: 'Invite User' },
        { name: 'removeUser', title: 'Remove User' },
        { name: 'deleteRoom', title: 'Delete Room' }
      ],
      styles: { container: { borderRadius: '4px' } }
      // ,dbRequestCount: 0
    }
  },
  computed: {
    loadedRooms() {
      // ROOMS == CONVERSATION
      // return this.rooms
      return this.rooms.slice(0, this.roomsLoadedCount)
    },
    screenHeight() {
      return this.isDevice ? window.innerHeight + 'px' : 'calc(100vh - 80px)'
    }
  },
  mounted() {
    this.fetchRooms()
    this.updateUserOnlineStatus()
  },
  methods: {
    resetRooms() {
      this.loadingRooms = true
      this.loadingLastMessageByRoom = 0
      this.roomsLoadedCount = 0
      this.rooms = []
      this.roomsLoaded = true
      this.startRooms = null
      this.endRooms = null
      this.roomsListeners.forEach(listener => listener())
      this.roomsListeners = []
      this.resetMessages()
    },
    resetMessages() {
      this.messages = []
      this.messagesLoaded = false
      this.startMessages = null
      this.endMessages = null
      this.listeners.forEach(listener => listener())
      this.listeners = []
    },
    fetchRooms() {
      this.resetRooms()
      this.fetchMoreRooms()
    },

    async fetchMoreRooms() {

      const rooms = [
        {
          roomId: 1,
          roomName: 'Room 1',
          avatar: 'assets/imgs/people.png',
          unreadCount: 4,
          lastUpdated: '2021-08-11 13:50:00',
          lastMessage: {
            content: 'Last message received',
            senderId: 1234,
            username: 'Kone Doe',
            timestamp: '10:20',
            saved: true,
            distributed: false,
            seen: false,
            new: true
          },
          users: [
            {
              _id: 1234,
              username: 'Kone Doe',
              avatar: 'https://66.media.tumblr.com/avatar_c6a8eae4303e_512.png',
              status: {
                state: 'online',
                lastChanged: 'today, 14:30'
              }
            },
            {
              _id: 4321,
              username: 'Traore Snow',
              avatar: 'https://avatarfiles.alphacoders.com/184/thumb-184913.jpg',
              status: {
                state: 'offline',
                lastChanged: '14 July, 20:00'
              }
            }
          ],
          typingUsers: [ 4321 ]
        }
      ];

      const roomUserIds = []
      rooms.forEach(room => {
        room.users.forEach(roomUser => {
          const foundUser = this.allUsers.find(user => user?._id === roomUser._id)
          if (!foundUser && roomUserIds.indexOf(roomUser._id) === -1) {
            roomUserIds.push(roomUser)
          }
        })
      })
      // this.incrementDbCounter('Fetch Room Users', roomUserIds.length)
      const rawUsers = []
      
      const getUser =  [
          {
            _id: 1234,
            username: 'Kone Doe',
            avatar: 'https://66.media.tumblr.com/avatar_c6a8eae4303e_512.png'
          },
          {
            _id: 4321,
            username: 'Traore Snow',
            avatar: 'https://avatarfiles.alphacoders.com/184/thumb-184913.jpg'
          },
          {
            _id: 1321,
            username: 'Nda Yoda',
            avatar:
              'https://vignette.wikia.nocookie.net/teamavatarone/images/4/45/Yoda.jpg/revision/latest?cb=20130224160049'
          }
        ];
        roomUserIds.forEach(roomUser => {
          // array1.forEach(element => console.log(element));
          const promise = getUser.find(user => user?._id === roomUser._id)
          // const found = array1.find(element => element > 10);
          rawUsers.push(promise)
        })
      
      this.allUsers = [...this.allUsers, ...(await Promise.all(rawUsers))];
      const roomList = []
      rooms.forEach(room => {
        roomList[room.roomId] = { ...room, users: [] }
        room.users.forEach(roomUser => {
          const foundUser = this.allUsers.find(user => user?._id === roomUser._id)
          if (foundUser) roomList[room.roomId].users.push(foundUser)
        })
      })
      const formattedRooms = []
      Object.keys(roomList).forEach(key => {
        const room = roomList[key]
        const roomContacts = room.users.filter(user => user?._id !== this.currentUserId)

        // alert(key);
        room.roomName = roomContacts.map(user => user.username).join(', ') || 'Myself'  
        const roomAvatar =roomContacts.length === 1 && roomContacts[0].avatar
            ? roomContacts[0].avatar : "null"
        formattedRooms.push({
          ...room,
          roomId: key,
          avatar: roomAvatar,
          lastUpdated: room.lastUpdated,
          lastMessage: {
            content: 'Room created',
            timestamp: this.formatTimestamp(room.lastUpdated)
          }
        })
      })
      this.rooms = this.rooms.concat(formattedRooms)
      console.log(this.rooms)
      formattedRooms.map(room => this.listenLastMessage(room))
      if (this.rooms.length > 0) {
        this.loadingRooms = false
        this.roomsLoadedCount = 0
      }
      this.listenUsersOnlineStatus(formattedRooms)
      // this.listenRooms(query)
    },
    listenLastMessage(room) {
      // const listener = messagesRef(room.roomId).orderBy('timestamp', 'desc').limit(1)
      //   .onSnapshot(messages => {
      //     // this.incrementDbCounter('Listen Last Room Message', messages.size)
      //     messages.forEach(message => {
      //       const lastMessage = this.formatLastMessage(message.data())
      //       const roomIndex = this.rooms.findIndex(
      //         r => room.roomId === r.roomId
      //       )
      //       this.rooms[roomIndex].lastMessage = lastMessage
      //       this.rooms = [...this.rooms]
      //     })
      //     if (this.loadingLastMessageByRoom < this.rooms.length) {
      //       this.loadingLastMessageByRoom++
      //       if (this.loadingLastMessageByRoom === this.rooms.length) {
      //         this.loadingRooms = false
      //         this.roomsLoadedCount = this.rooms.length
      //       }
      //     }
      //   })
      // this.roomsListeners.push(listener)
    },
    formatLastMessage(message) {
      if (!message.timestamp) return
      let content = message.content
      const timestamp = new Date(message.created_at)
      if (message.files?.length) {
        const file = message.files[0]
        content = `${file.name}.${file.extension || file.type}`
      }

      return {
        ...message,
        ...{
          content,
          seconds: date.format(timestamp, 'ss'),
          timestamp: date.format(timestamp, 'HH:mm'),
          date: date.format(timestamp, 'DD MMMM YYYY'),
          distributed: true,
          seen: message.senderId === this.currentUserId ? message.seen : null,
          new:
            message.senderId !== this.currentUserId &&
            (!message.seen || !message.seen[this.currentUserId])
        }
      }
    },
    formatTimestamp(dateString) {
      const timestamp = new Date(dateString)
      const timestampFormat = date.isSameDay(timestamp, new Date()) ? 'HH:mm' : 'DD/MM/YY'
      const result = date.format(timestamp, timestampFormat); 
      return timestampFormat === 'HH:mm' ? `Today, ${result}` : result
    },
    fetchMessages({ room, options = {} }) {
  
      const messages = [
          {
            _id: 7890,
            indexId: 12092,
            content: 'Message 1',
            senderId: 1234,
            username: 'John Doe',
            avatar: 'assets/imgs/doe.png',
            created_at: '2021-07-23 19:17:21',
            system: false,
            saved: true,
            distributed: true,
            seen: true,
            deleted: false,
            disableActions: false,
            disableReactions: false,
            files: [
              {
                name: 'My File',
                size: 67351,
                type: 'png',
                audio: true,
                duration: 14.4,
                url: 'https://firebasestorage.googleapis.com/...',
                preview: 'data:image/png;base64,iVBORw0KGgoAA...'
              }
            ],
            reactions: {
              "😁": [
                1234, // USER_ID
                4321
              ],
              "🥰": [
                1234
              ]
            },
            replyMessage: {
              content: 'Reply Message',
              senderId: 4321,
              files: [
                {
                  name: 'My Replied File',
                  size: 67351,
                  type: 'png',
                  audio: true,
                  duration: 14.4,
                  url: 'https://firebasestorage.googleapis.com/...',
                  preview: 'data:image/png;base64,iVBORw0KGgoAA...'
                }
              ]
            },
          }
      ];
      if (options.reset) this.messages = []
        messages.forEach(message => {
          const formattedMessage = this.formatMessage(room, message)
          console.log(formattedMessage)
          this.messages.unshift(formattedMessage)
          this.messagesLoaded = true
        })
    },
    listenMessages(messages, room) {
      messages.forEach(message => {
        const formattedMessage = this.formatMessage(room, message)
        const messageIndex = this.messages.findIndex(m => m._id === message.id)
        if (messageIndex === -1) {
          this.messages = this.messages.concat([formattedMessage])
        } else {
          this.messages[messageIndex] = formattedMessage
          this.messages = [...this.messages]
        }
        this.markMessagesSeen(room, message)
      })
    },
    markMessagesSeen(room, message) {
      if (
        message.senderId !== this.currentUserId &&
        (!message.seen || !message.seen[this.currentUserId])
      ) {
        // messagesRef(room.roomId).doc(message.id) .update({         
        //     [`seen.${this.currentUserId}`]: new Date()
        //   })
      }
    },
    formatMessage(room, message) {
      const senderUser = room.users.find(user => message.senderId === user._id  )
      const timestamp = new Date(message.created_at)
      const formattedMessage = {
        ...message,
        ...{
          senderId: message.senderId,
          _id: message._id,
          seconds: date.format(timestamp, 'ss'),
          timestamp: date.format(timestamp, 'HH:mm'),
          date: date.format(timestamp, 'DD MMMM YYYY'),
          username: senderUser ? senderUser.username : null,
          avatar: senderUser ? senderUser.avatar : null,
          distributed: true
        }
      }
      if (message.replyMessage) {
        formattedMessage.replyMessage = {
          ...message.replyMessage,
          ...{
            senderId: message.replyMessage.senderId
          }
        }
      }
      return formattedMessage
    },
    async sendMessage({ content, roomId, files, replyMessage }) {
      const message = {
        senderId: this.currentUserId,
        content,
        created_at: new Date()
      }
      if (files) {
        message.files = this.formattedFiles(files)
      }
      if (replyMessage) {
        message.replyMessage = {
          _id: replyMessage._id,
          content: replyMessage.content,
          senderId: replyMessage.senderId
        }
        if (replyMessage.files) {
          message.replyMessage.files = replyMessage.files
        }
      }
      if (files) {
        for (let index = 0; index < files.length; index++) {
          await this.uploadFile({ file: files[index], messageId: id, roomId })
        }
      }

      // const { id } = await messagesRef(roomId).add(message)
      // const found = array1.find(user => message.senderId === user._id);
      // roomsRef.doc(roomId).update({ lastUpdated: new Date() })
    },
    async editMessage({ messageId, newContent, roomId, files }) {
      const newMessage = { edited: new Date() }
      newMessage.content = newContent
      if (files) {
        newMessage.files = this.formattedFiles(files)
      } else {
        newMessage.files = deleteDbField
      }
      if (files) {
        for (let index = 0; index < files.length; index++) {
          if (files[index]?.blob) {
            await this.uploadFile({ file: files[index], messageId, roomId })
          }
        }
      }
      // 
      // await messagesRef(roomId).doc(messageId).update(newMessage)
      // 
    },
    async deleteMessage({ message, roomId }) {
      const { files } = message
      if (files) {
        // files.forEach(file => {
        //   const deleteFileRef = filesRef
        //     .child(this.currentUserId)
        //     .child(message._id)
        //     .child(`${file.name}.${file.extension || file.type}`)
        //   deleteFileRef.delete()
        // })
      }
      // 
      // await messagesRef(roomId).doc(message._id).update({ deleted: new Date() })
      // 
    },
    async uploadFile({ file, messageId, roomId }) {
      
    },
    formattedFiles(files) {
      const formattedFiles = []
      files.forEach(file => {
        const messageFile = {
          name: file.name,
          size: file.size,
          type: file.type,
          extension: file.extension || file.type,
          url: file.url || file.localUrl
        }
        if (file.audio) {
          messageFile.audio = true
          messageFile.duration = file.duration
        }
        formattedFiles.push(messageFile)
      })
      return formattedFiles
    },
    openFile({ file }) {
      window.open(file.file.url, '_blank')
    },
    async openUserTag({ user }) {
      
    },
    async loadRoom(query) {
      
    },
    menuActionHandler({ action, roomId }) {
      switch (action.name) {
        case 'inviteUser':
          return this.inviteUser(roomId)
        case 'removeUser':
          return this.removeUser(roomId)
        case 'deleteRoom':
          return this.deleteRoom(roomId)
      }
    },
    async sendMessageReaction({ reaction, remove, messageId, roomId }) {
      
    },
    typingMessage({ message, roomId }) {
      
    },
    async listenRooms(query) {
      
    },
    updateUserOnlineStatus() {
      
    },
    listenUsersOnlineStatus(rooms) {
      
    },
    addRoom() {
      this.resetForms()
      this.addNewRoom = true
    },
    async createRoom() {
      
    },
    inviteUser(roomId) {
      
    },
    async addRoomUser() {
      
    },
    removeUser(roomId) {
      
    },
    async deleteRoomUser() {
      
    },
    async deleteRoom(roomId) {
      
    },
    resetForms() {
      this.disableForm = false
      this.addNewRoom = null
      this.addRoomUsername = ''
      this.inviteRoomId = null
      this.invitedUsername = ''
      this.removeRoomId = null
      this.removeUserId = ''
    }
  }
}
</script>
<style lang="scss" scoped>
.window-container {
  width: 100%;
}
.window-mobile {
  form {
    padding: 0 10px 10px;
  }
}
form {
  padding-bottom: 20px;
}
input {
  padding: 5px;
  width: 140px;
  height: 21px;
  border-radius: 4px;
  border: 1px solid #d2d6da;
  outline: none;
  font-size: 14px;
  vertical-align: middle;
  &::placeholder {
    color: #9ca6af;
  }
}
button {
  background: #1976d2;
  color: #fff;
  outline: none;
  cursor: pointer;
  border-radius: 4px;
  padding: 8px 12px;
  margin-left: 10px;
  border: none;
  font-size: 14px;
  transition: 0.3s;
  vertical-align: middle;
  &:hover {
    opacity: 0.8;
  }
  &:active {
    opacity: 0.6;
  }
  &:disabled {
    cursor: initial;
    background: #c6c9cc;
    opacity: 0.6;
  }
}
.button-cancel {
  color: #a8aeb3;
  background: none;
  margin-left: 5px;
}
select {
  vertical-align: middle;
  height: 33px;
  width: 152px;
  font-size: 13px;
  margin: 0 !important;
}
</style>
Now i have to do the backend. sorry help me please

**Comment by soumsena** [comment]
I am using the [vue-advanced-chat](https://github.com/antoine92190/vue-advanced-chat) package  like the Frontend.
here is an example of my component
[chat.txt](https://github.com/myckhel/laravel-chat-system/files/7164738/chat.txt)
Now i have to do the backend. sorry help me please

**Comment by myckhel** [comment]
What exactly did you want me to help you with?

**Comment by myckhel** [comment]
Feel free to re-open when needed.
