### ISSUE TITLE
Fix Inconsistent tests

### ISSUE THREAD

**Issue by myckhel** [myckhel/laravel-chat-system#41]

**Comment by hmreumann** [comment]
@myckhel Hallo, how are you? Do you need help with something? I might have some time available!!

**Comment by myckhel** [comment]
@hmreumann is Back 😄 .

When you run `composer test` sometimes the test fails sometimes it passes.
example failure https://github.com/myckhel/laravel-chat-system/runs/4200726413?check_suite_focus=true

This needs debugging to fix.

I can assign to you if you wanna try debug.

**Comment by hmreumann** [comment]
Sure @myckhel It is going to be good for me to try Pest

**Comment by myckhel** [comment]
Thanks @hmreumann for your efforts
