### ISSUE TITLE
change service provider's publish config name from `chat-system.config` to `config`

### ISSUE THREAD

**Issue by myckhel** [myckhel/laravel-chat-system#9]
Running `php artisan vendor:publish --provider="Myckhel\ChatSystem\ChatSystemServiceProvider" --tag='config'`  [per the doc](https://myckhel.github.io/laravel-chat-system/docs/install/#publishing-the-config-file): results in error: `Unable to locate publishable resources`.

Changing the name will fix.

**Comment by hmreumann** [comment]
Hallo, how are you? I think I can help you with this.

**Comment by myckhel** [comment]
Oh Nice!🙂

Ive assigned you.
